(rocq.theory
 (name Sail)
; (package rocq-sail)
 (modules
   Inhabited
   MachineWordInterface
   TypeCasts
   MachineWord
   Instances
   Instr_kinds
   Values
   Values_lemmas
   GenericValue
   String
   Prompt_monad
   Prompt
   State
   State_lemmas
   State_monad
   State_monad_lemmas
   State_lifting
   Hoare
   Undefined
   Operators_mwords
   Base
   Real
   Impl_base
 )
 (theories Stdlib bbv)
 (rocqdoc_flags :standard --utf8
               --external https://rocq-prover.org/doc/V9.0.0/stdlib/ Stdlib
               --coqlib_url https://rocq-prover.org/doc/V9.0.0/corelib/
 )
)

(alias
 (name bbv)
 (deps (alias all))
)
