(rocq.theory
 (name SailStdpp)
 (package rocq-sail-stdpp)
 (modules
   Inhabited
   MachineWordInterface
   TypeCasts
   MachineWord
   Values
   GenericValue
   Instances
   Instr_kinds
   Values_lemmas
   String
   Prompt_monad
   Prompt
   State
   State_monad
   State_lemmas
   State_monad_lemmas
   State_lifting
   Hoare
   Undefined
   Operators_mwords
   Base
   Real
   Impl_base
   ConcurrencyInterfaceBuiltins
   ConcurrencyInterfaceTypes
   ConcurrencyInterface
   ConcurrencyInterfaceTypesV2
   ConcurrencyInterfaceBuiltinsV2
   ConcurrencyInterfaceV2
 )
 (theories Stdlib stdpp stdpp.bitvector)
 (rocqdoc_flags :standard --utf8
               --external https://plv.mpi-sws.org/coqdoc/stdpp/ stdpp
               --external https://rocq-prover.org/doc/V9.0.0/stdlib/ Stdlib
               --coqlib_url https://rocq-prover.org/doc/V9.0.0/corelib/
 )
)

(subdir tests
 (rocq.theory
  (name SailStdpp.tests)
  (modules MachineWordTest)
  (theories stdpp stdpp.bitvector SailStdpp)
 )
 (rule (copy ../MachineWordTest.v MachineWordTest.v))
 (alias
  (name runtest)
  (deps (alias all))
 )
)

(alias
 (name stdpp)
 (deps (alias all))
)
